version: '3'
services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    hostname: mysql
    ports:
      - "33060:3306"
    environment:
      MYSQL_USER: gopher
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gopher
    command: mysql --character-set-server=utf8mb4 --collaction-server=utf8mb4_unicode_ci --skip-charaset-client-handshake
    volumes:
      - "db-data:var/lib/mysql"
      - "./docker/mysql/my.conf:./etc/mysql/my.conf"
      - "./docker/mysql/init/:/docker-entry-point-initdb.d"
  web:
    links:
      - mysql
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: gopher-training
    ports:
      - "80800:8080"
    volumes:
      - .:/go/src/gopher-training
    command: sh ./start_app.sh
volumes:
  db-data:
    driver: local